version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      ALLOW_ORIGINS: ${ALLOW_ORIGINS}
      TZ: ${TZ}
      OPENAPI_ENABLED: ${OPENAPI_ENABLED:-1}
    ports:
      - "5000:5000"
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"